import { readFileSync, writeFileSync } from 'node:fs';
import { ConfigsManager } from 'sborshik/utils';
import { defineLibViteConfig } from 'sborshik/vite';

export default defineLibViteConfig(ConfigsManager.create(), {
  omitStrangeExportEntries: true,
  async customPluginBeforeFinish() {
    try {
      console.log('\n📝 Generating utility types global file...\n');

      const utilTypesContent = readFileSync('dist/types.d.ts', {
        encoding: 'utf-8',
      }).toString();

      const processedContent = [
        '/** THIS IS AUTOGENERATED FILE FROM "utils/types.ts" */',
        utilTypesContent
          .split('\n')
          .filter((line) => !line.startsWith('export type {'))
          .join('\n')
          .replaceAll('export type', 'type'),
      ].join('\n');

      writeFileSync('dist/types.global.d.ts', processedContent);

      console.log('✅ Generated types.global.d.ts\n');
    } catch (error) {
      console.error('❌ Failed to generate utility types:', error);
    }
  },
});
