#!/usr/bin/env tsx

import { readFileSync, writeFileSync } from "node:fs";

function generateUtilityTypesFile() {
  const utilTypesContent = readFileSync('dist/utils/types.d.ts', { encoding: 'utf-8'}).toString()

  writeFileSync(
    'dist/utility-types.d.ts',
    [
      '/** THIS IS AUTOGENERATED FILE FROM "utils/types.ts" */',
      utilTypesContent.split('\n').filter(it => !it.startsWith('export type {')).join('\n').replaceAll('export type', 'type')
    ].join('\n')
  )

  console.log('generated utility types file OK');
}

// Run the script
generateUtilityTypesFile();