/**
 * ---header-docs-section---
 * # yummies/types.global
 *
 * ## Description
 *
 * Build artifact that mirrors **`yummies/types`** into ambient global declarations for projects
 * that prefer not to import utility types at every file. The runtime module is empty (`export {}`);
 * consume it via the generated `.d.ts` bundle in `dist` after `pnpm build`, not as executable JS.
 *
 * ## Usage
 *
 * ```ts
 * /// <reference types="yummies/types.global" />
 * ```
 */

/** THIS IS AUTOGENERATED FILE from utils/types.ts */

export {};
